version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    command: node index.js config.xml [-v]
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379
